controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute




index :
    path: /index
    controller: App\Controller\IndexController::index

artistes :
    path: /artistes
    controller: App\Controller\ArtistesController::index

Connexion :
    path: /connexion
    controller: App\Controller\ConnexionController::index